### ISSUE TITLE
Biological variants of genes not explicitly referred to the human taxon 

### ISSUE THREAD

**Issue by floatingpurr** [SuLab/GeneWikiCentral#61]
Hello once again. I was trying to get all biological variants (`P3433`) of human genes in wikidata when I realized that some of them (17 right now) are referred to genes that do not have the statement:

`gene` `found in taxon (P3433)` `Homo sapiens (Q15978631)`

[Here](http://tinyurl.com/y7w4jffj) is a query to see such a behavior in action. From a theoretical point of view, I expected all human genes explicitly referred to their taxon. I'm quite new to wikidata, so I don't know if that is perfectly normal or not. Isn't there a kind of ShEx to formalize data constraints?

**Comment by stuppie** [comment]
Hi floatingpurr,
There as a bug in handling of genes that encode more than one protein. I've implemented it and these should get corrected by the bot by tomorrow.

**Comment by floatingpurr** [comment]
Hi stuppie,
thank you! Please note that the taxon property seems still missing in [`Q14874282`](https://www.wikidata.org/wiki/Q14874282) and in [`Q18033471`](https://www.wikidata.org/wiki/Q18033471)

**Comment by stuppie** [comment]
The [bot](http://jenkins.sulab.org/job/GeneBot_Homo_sapiens/51/consoleText) is still running, should be done in 3 hrs.

**Comment by floatingpurr** [comment]
There are just few genes left without the `P3433`. I don't know if it's ok or if there is a piece of bug still there.

**Comment by stuppie** [comment]
@floatingpurr Check out this page [here](http://jenkins.sulab.org/job/GeneBot_Homo_sapiens/51/artifact/scheduled-bots/scheduled_bots/geneprotein/logs/GeneBot-20170907_23:00.html) for a log of the latest bot run. This is a work in progress, but they should all be showing up [here](https://www.wikidata.org/wiki/User:ProteinBoxBot/Bot_Status) eventually.
You can see 666 out of 58,753 items were skipped due to some failure/conflict. The two left have some ID conflicts and need to be manually fixed..

**Comment by andrewsu** [comment]
Looks like someone fixed the human examples -- thanks!  Closing...
